#! /bin/sh
function fatal {
	echo $1;
	exit 1;
}

function SOURCE {
	test $PACKAGE_FILTER && test x$PACKAGE_FILTER != x$1 && return;
	PKG=$1
	STRIP=$2
	FORMAT=$3
	URL=$4
	mkdir -p $abs_tarballdir
	if test x$SKIPDOWNLOAD != xyes; then
		wget -O $abs_tarballdir/$PKG $URL || fatal "URL not found"
	fi
	mkdir -p $depdir/$PKG
	tar -$FORMAT -xf $abs_tarballdir/$PKG --strip-components $STRIP -C $depdir/$PKG
}

function PREPARE {
	test $PACKAGE_FILTER && test x$PACKAGE_FILTER != x$1 && return;
	if test -x prepare-$1; then
		(
		cd $depdir/$1;
		. $abs_bootstrapdir/prepare-$1;
		)
	else
		fatal "prepare-$1" script is not found.
	fi;
}

function PATCH {
	test $PACKAGE_FILTER && test x$PACKAGE_FILTER != x$1 && return;
	if test -x patch-$1; then
		(
		cd $depdir/$1;
		. $abs_bootstrapdir/patch-$1;
		)
	else
		fatal "patch-$1" script is not found.
	fi;
}

function noinst_libraries {
	AMs=`find . -name 'Makefile.am'`
	for AM in $AMs; do
		mv $AM $AM.bak
		cat $AM.bak | sed 's;lib_LTLIBRARIES;noinst_LTLIBRARIES;g' > $AM
	done;
	ln -sf $abs_bootstrapdir/default-configure configure.gnu
}
