#! /bin/sh
# this script bootstraps the building process by loading all dependency
# to dependency subdir

top_srcdir=`dirname $0`/..
bootstrapdir=`dirname $0`
abs_bootstrapdir=`readlink -f $bootstrapdir`
abs_chroot=$abs_bootstrapdir/root
abs_patchdir=$abs_bootstrapdir/patches
abs_tarballdir=$abs_bootstrapdir/tarballs
depdir=$top_srcdir/dependency

. $bootstrapdir/bootstrap-functions

if test $1; then
	PACKAGE_FILTER=$1
fi

. $bootstrapdir/bootstrap.conf
