LDADD = $(GLIB_LIBS) \
		$(GSL_LIBS) \
		$(top_builddir)/gtkbuilder/libgtkbuilder.la 

AM_CPPFLAGS = $(GLIB_CFLAGS) $(GSL_CFLAGS) -I$(top_srcdir) -I$(top_srcdir)/ucntracker

SUFFIXES = .c .vala
.vala.c:
	$(VALAC) -C $< $(VAPIDEPENDS) --pkg gsl $(top_srcdir)/gtkbuilder/libgtkbuilder.vapi
	touch $@

check-local:
	for i in $(noinst_PROGRAMS); do \
		./$$i; \
    done;
