
AM_CPPFLAGS = $(GLIB_CFLAGS) $(GSL_CFLAGS) -I$(top_srcdir) -I$(top_srcdir)/ucntracker
AM_LDFLAGS = -export-dynamic -rdynamic

SUFFIXES = .c .vala
.vala.c:
	$(VALAC) -C $< $(VAPIDEPENDS) --pkg gsl 
	touch $@

check-local:
	for i in $(noinst_PROGRAMS); do \
		./$$i; \
    done;
