COMPILEDSOURCES=$(VALASOURCES:.vala=.c) \
			   $(VALASOURCES:.vala=.h)

AM_CPPFLAGS = $(GLIB_CFLAGS) $(GSL_CFLAGS) \
				-I$(top_srcdir) -I$(top_srcdir) \
				-I$(top_srcdir)/ucntracker \
				-include config.h

BUILT_SOURCES = vala-stamp

vala-stamp: $(VALASOURCES)
	$(VALAC) --library=$(VAPINAME) --basedir=$(top_srcdir)/ucntracker -C --vapidir=$(top_srcdir)/ucntracker/core $^ $(VAPIDEPENDS) --pkg gsl --pkg core
	touch $@
